import {identityKey,sameProduct,validBarcode} from '@/lib/product-match';
import {context,errorResponse,getProducts} from '@/lib/server';
import {Product,freshProduct,project,units,categories,sydneyDate,deadline} from '@/lib/inventory';
function number(v:any,min=0,max=1e7){if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw new Error('Please enter a valid amount.');return v;}
function str(v:any,max=240){return String(v??'').trim().slice(0,max);}
export async function POST(req:Request){try{const {owner,db}=await context(req);const body=await req.json() as any;const {kind}=body;const requestId=str(body.requestId,100);if(!/^[\w-]{10,100}$/.test(requestId))throw new Error('Update reference is missing. Please try again.');const eventId=owner+':'+requestId;const duplicate=await db.prepare('SELECT id FROM events WHERE id=? AND owner=?').bind(eventId,owner).first();if(duplicate)return Response.json({ok:true,duplicate:true});const now=Date.now();let p:Product;let previous:Product|null=null;const id=str(body.productId||crypto.randomUUID(),100);const key=owner+':'+id;const row=await db.prepare('SELECT data,version FROM products WHERE key=? AND owner=?').bind(key,owner).first<{data:string;version:number}>();if(kind==='create'){if(row)throw new Error('This product already exists.');p=freshProduct(id,str(body.values?.name),str(body.values?.category)||'Groceries');}else{if(!row)throw new Error('Product not found.');p={...JSON.parse(row.data),version:row.version};if(body.version!==p.version)throw new Error('This item changed on another screen. Refresh it before saving.');previous=structuredClone(p);p.batches=project(p,now).batches;p.stockAt=now;}
if(kind==='create'||kind==='edit'){const v=body.values||{};p.name=str(v.name||p.name);if(!p.name)throw new Error('Add a product name.');p.category=categories.includes(v.category)?v.category:p.category;for(const f of ['brand','variant','sku','aliases','notes'] as const)p[f]=str(v[f],f==='notes'?1000:240);const nextUnit=str(v.unit,20);if(nextUnit&&!units.includes(nextUnit))throw new Error('Choose a valid unit.');if(previous?.stockKnown&&previous.unit!==nextUnit)throw new Error('Stock units are locked once stock is recorded. Add a new product for a different unit.');p.unit=nextUnit;for(const f of ['packSize','dailyUse'] as const)p[f]=v[f]===null||v[f]===''||v[f]===undefined?null:number(v[f],f==='packSize'?.00001:0);for(const f of ['leadDays','bufferDays','targetDays'] as const)p[f]=number(v[f]??p[f],f==='targetDays'?1:0,3660);if(typeof v.archived==='boolean')p.archived=v.archived;}
if(kind==='create'||kind==='edit'){const v=body.values||{};p.barcode=str(v.barcode,30);if(p.barcode&&!validBarcode(p.barcode))throw new Error('Check the barcode digits. Use SKU for a retailer code.');p.productName=str(v.productName);p.productSource=str(v.productSource);p.productUrl=str(v.productUrl,1200);if(p.productUrl){let u:URL;try{u=new URL(p.productUrl)}catch{throw new Error('Enter a valid product link.');}if(u.protocol!=='https:')throw new Error('Use an https product link.');}const existing=(await getProducts(db,owner)).find(other=>other.id!==p.id&&!other.archived&&sameProduct(p,other));if(existing)return Response.json({error:'This product is already saved as '+existing.name+'. Open that item to update it.',duplicateId:existing.id},{status:409});}
let summary='';let amount:number|null=null;const quantity=body.quantity===null||body.quantity===undefined?null:number(body.quantity);const expiry=str(body.expiry,10);if(expiry&&!/^\d{4}-\d{2}-\d{2}$/.test(expiry))throw new Error('Choose a valid label date.');if(expiry&&(Number.isNaN(Date.parse(expiry))||new Date(expiry).toISOString().slice(0,10)!==expiry))throw new Error('Choose a valid label date.');const dateType=['Use by','Best before','Expiry'].includes(body.dateType)?body.dateType:'Expiry';
if(kind==='count'||kind==='purchase'){if(!p.unit)throw new Error('Set this product’s stock unit first.');if(quantity===null)throw new Error('Enter a quantity.');if(kind==='purchase'&&quantity<=0)throw new Error('Purchase quantity must be more than zero.');if(kind==='purchase'&&!p.stockKnown)throw new Error('Set your current stock first, even if it is zero.');if(expiry&&expiry<sydneyDate(now)&&kind==='purchase')throw new Error('This label date is in the past. Check it before recording a new purchase.');const batch={id:crypto.randomUUID(),quantity,expiry,dateType,openedAt:null,afterOpeningDays:null};if(kind==='count'){p.batches=quantity>0?[batch]:[];p.stockKnown=true;p.lastCountAt=now;summary='Stock checked: '+quantity+' '+p.unit;}else{p.batches.push(batch);p.shopping=false;amount=body.amount===null||body.amount===undefined?null:number(body.amount);summary='Bought '+quantity+' '+p.unit;}p.stockAt=now;}
if(kind==='finish'){if(!p.stockKnown)throw new Error('Set your stock first.');const batch=p.batches.find(b=>b.id===body.batchId);if(!batch)throw new Error('Choose which batch you finished.');batch.quantity=0;summary='Finished selected batch';}
if(kind==='open'){const batch=p.batches.find(b=>b.id===body.batchId);if(!batch||batch.quantity<=0||deadline(batch)<=now)throw new Error('Choose an available batch.');if(batch.openedAt)throw new Error('This batch is already opened. Its opening clock cannot be restarted.');const opening=body.wholeBatch===true?batch.quantity:number(quantity,.00001,batch.quantity);const days=body.afterOpeningDays===null||body.afterOpeningDays===''||body.afterOpeningDays===undefined?null:number(body.afterOpeningDays,1,3660);if(opening<batch.quantity){batch.quantity-=opening;p.batches.push({...batch,id:crypto.randomUUID(),quantity:opening,openedAt:now,afterOpeningDays:days});}else{batch.openedAt=now;batch.afterOpeningDays=days;}summary='Opened '+opening+' '+p.unit;}
if(kind==='shopping'){p.shopping=!!body.selected;summary=p.shopping?'Added to shopping list':'Removed from shopping list';}
if(kind==='undo'){const latest=await db.prepare('SELECT id,data FROM events WHERE owner=? AND product_key=? ORDER BY at DESC LIMIT 1').bind(owner,key).first<any>();if(!latest||latest.id!==body.undoId)throw new Error('Only the most recent change to this item can be undone.');const d=JSON.parse(latest.data);if(!d.previous)throw new Error('This change cannot be undone.');const oldVersion=p.version;p={...d.previous,version:oldVersion};summary='Undid '+d.summary;}
if(!['create','edit','count','purchase','finish','open','shopping','undo'].includes(kind))throw new Error('Unknown update type.');if(!summary)summary=kind==='create'?'Product added':'Product details updated';const event={productName:p.name,summary,quantity,unit:p.unit,amount,store:str(body.store),receiptId:str(body.receiptId,140),previous,source:body.source==='Siri'?'Siri':'Website',afterVersion:p.version+1};const matchKey=p.archived?null:identityKey(p);const data=JSON.stringify({...p,version:undefined});const statements=kind==='create'?[db.prepare('INSERT INTO products(key,owner,data,version,last_op,identity_key) VALUES(?,?,?,1,?,?)').bind(key,owner,data,eventId,matchKey)]:[db.prepare('UPDATE products SET data=?,version=version+1,last_op=?,identity_key=? WHERE key=? AND owner=? AND version=?').bind(data,eventId,matchKey,key,owner,p.version)];statements.push(db.prepare('INSERT INTO events(id,owner,product_key,kind,at,data) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM products WHERE key=? AND last_op=?)').bind(eventId,owner,key,kind,now,JSON.stringify(event),key,eventId));const result=await db.batch(statements);if(!result[0].meta.changes)throw new Error('This item changed while saving. Refresh and try again.');return Response.json({ok:true});}catch(e){if(String(e).includes('UNIQUE constraint failed: products.owner, products.identity_key'))return Response.json({error:'This product is already in your list. Refresh and open the existing item.'},{status:409});return errorResponse(e);}}
