'use client';
import {useRef,useState,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Search,Loader2,ExternalLink,Check} from 'lucide-react';
import type {Product} from '@/lib/inventory';
import {CatalogProduct,normal,quantityIn,sameProduct} from '@/lib/product-match';
export default function ProductLookup({edit,setEdit,products,openExisting,initialQuery}:{edit:any;setEdit:(value:any)=>void;products:Product[];openExisting:(p:Product,q:string)=>void;initialQuery:string}){
 const [query,setQuery]=useState(initialQuery),[results,setResults]=useState<CatalogProduct[]>([]),[busy,setBusy]=useState(false),[searched,setSearched]=useState(false),[message,setMessage]=useState(''),[selected,setSelected]=useState('');
 const request=useRef<AbortController|null>(null),lastSearch=useRef(0);
 useEffect(()=>()=>request.current?.abort(),[]);
 const existing=products.filter(p=>!p.archived&&p.id!==edit.id&&query.trim().length>=3&&[p.name,p.brand,p.productName||'',...p.aliases.split(',')].some(n=>normal(n).length>=3&&(normal(query).includes(normal(n))||normal(n).includes(normal(query))))) .slice(0,3);
 async function search(){if(busy)return;if(Date.now()-lastSearch.current<6500){setMessage('Please wait a few seconds before another search.');return;}lastSearch.current=Date.now();request.current?.abort();const ctrl=new AbortController();request.current=ctrl;setBusy(true);setMessage('');setResults([]);setSelected('');setSearched(false);try{const r=await fetch('/api/products/search?'+new URLSearchParams({q:query,category:edit.category}),{signal:ctrl.signal});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Search unavailable.');setResults(d.results);setMessage(d.warning||'');setSearched(true);}catch(e){if((e as Error).name!=='AbortError'){setMessage((e as Error).message);setSearched(true);}}finally{if(!ctrl.signal.aborted)setBusy(false);}}
 function values(r:CatalogProduct){return {name:edit.name||r.name,brand:r.brand,variant:r.variant,productName:[r.brand,r.name].filter(Boolean).join(' '),barcode:r.barcode,packSize:r.packSize,unit:r.unit};}
 function choose(r:CatalogProduct){const same=products.find(p=>p.id!==edit.id&&!p.archived&&sameProduct(values(r),p));if(same){openExisting(same,query);return;}const unit=edit.stockKnown?edit.unit:r.unit||edit.unit;const packSize=edit.stockKnown?quantityIn(r.packSize,r.unit,unit):r.packSize;setEdit({...edit,...values(r),unit,packSize,sku:'',productUrl:r.url,productSource:r.source,aliases:[...new Set([edit.aliases||'',edit.name,r.name,r.brand+' '+r.name].filter(Boolean))].join(', ').slice(0,240)});setSelected(r.id);setMessage(edit.stockKnown&&r.packSize&&packSize===null?'Product details filled in. Enter the pack size in your existing stock unit; stock has not changed.':'Details filled in. Check the size and variant, then save.');}
 return <section className="product-lookup"><div className="lookup-title"><Search size={18}/><h2>Find your exact product</h2></div><div className="lookup-search"><Input aria-label="Product name or barcode" value={query} maxLength={120} onChange={e=>{request.current?.abort();setBusy(false);setQuery(e.target.value);setSearched(false);setResults([]);setMessage('');}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();search();}}} placeholder="e.g. Rokeby Fitmilk Lite, or a barcode"/><Button type="button" onClick={search} disabled={busy||query.trim().length<2}>{busy?<Loader2 className="animate-spin"/>:<Search/>}Search</Button></div>
 {existing.length>0&&<div className="existing-matches"><p>Already in your list</p>{existing.map(p=><button type="button" key={p.id} onClick={()=>openExisting(p,query)}>Open {p.name}{p.brand?' · '+p.brand:''}</button>)}</div>}
 {busy&&<p role="status" className="muted">Searching online catalogues…</p>}{message&&<p role="status" className="lookup-message">{message}</p>}
 {results.length>0&&<div className="lookup-results">{results.map(r=>{const duplicate=products.find(p=>p.id!==edit.id&&!p.archived&&sameProduct(values(r),p));return <article className={'lookup-result '+(selected===r.id?'chosen':'')} key={r.id}><div><strong>{r.brand} {r.name}</strong><p>{r.quantityLabel||'Pack size to confirm'}{r.barcode?' · '+r.barcode:''}</p><a href={r.url} target="_blank" rel="noreferrer">{r.source}<ExternalLink size={13}/></a></div><Button type="button" variant={selected===r.id?'default':'outline'} size="sm" onClick={()=>choose(r)}>{selected===r.id?<><Check/>Selected</>:duplicate?'Open existing':'Use this'}</Button></article>})}</div>}
 {searched&&!busy&&!results.length&&!message&&<p className="muted">No catalogue match. Try the brand or barcode, or search the web below.</p>}
 <p className="lookup-help">Catalogue details may be incomplete. Check the label before saving.</p><div className="lookup-links"><a href={'https://www.google.com/search?q='+encodeURIComponent((query||edit.name)+' Australia product pack size')} target="_blank" rel="noreferrer">Search the web <ExternalLink size={13}/></a><a href="https://world.openfoodfacts.org/data" target="_blank" rel="noreferrer">Open Facts data · ODbL</a></div>
 </section>;
}
