import {context,errorResponse} from '@/lib/server';
import {CatalogProduct,parsePack,validBarcode,normal} from '@/lib/product-match';
const reference:CatalogProduct={id:'rokeby-fitmilk-light-1l',name:'FitMilk Light',brand:'Rokeby',variant:'FitMilk Light · Lactose free',packSize:1,unit:'L',barcode:'',url:'https://rokebynutrition.com/products/fitmilk-light',source:'Rokeby · manufacturer reference',quantityLabel:'1 L'};
const headers={'User-Agent':'PowerCart/1.0 (personal inventory; https://github.com/albertsingh03/powercart)','Accept':'application/json'};
async function getJSON(url:string){const r=await fetch(url,{headers,cache:'no-store',signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error('Catalogue unavailable');return r.json() as Promise<any>;}
function mapProduct(p:any,source:string,host='world.openfoodfacts.org'):CatalogProduct|null{const name=String(p.product_name_en||p.product_name||'').trim().slice(0,240);if(!name)return null;const brand=(Array.isArray(p.brands)?p.brands.join(', '):String(p.brands||'')).slice(0,160);const quantityLabel=String(p.quantity||'').slice(0,80);return {id:host+':'+String(p.code),name,brand,variant:name,...parsePack(quantityLabel),quantityLabel,barcode:validBarcode(String(p.code||'')),url:'https://'+host+'/product/'+encodeURIComponent(p.code),source};}
export async function GET(req:Request){try{await context();const input=new URL(req.url).searchParams;const q=(input.get('q')||'').trim().slice(0,120);if(q.length<2)return Response.json({error:'Enter at least two characters.'},{status:400});const category=input.get('category')||'Groceries';const isBarcode=/^[\d\s-]{8,20}$/.test(q);if(isBarcode&&!validBarcode(q))return Response.json({error:'Check the barcode digits and try again.'},{status:400});
let results:CatalogProduct[]=[],warning='';const matchesReference=!isBarcode&&q.toLowerCase().split(/\s+/).every(word=>normal('Rokeby FitMilk Light Lite milk lactose free 1L').includes(normal(word)));
if(matchesReference)results.push(reference);
try{if(isBarcode){const code=validBarcode(q);const d=await getJSON('https://world.openfoodfacts.org/api/v3/product/'+code+'?product_type=all');const p=d.product;if(p){const type=String(p.product_type||d.product_type||'food');const host=type==='beauty'?'world.openbeautyfacts.org':type==='petfood'?'world.openpetfoodfacts.org':type==='product'?'world.openproductsfacts.org':'world.openfoodfacts.org';const v=mapProduct(p,'Open '+(type==='beauty'?'Beauty':type==='petfood'?'Pet Food':type==='product'?'Products':'Food')+' Facts',host);if(v)results.push(v);}}
else if(category==='Personal care'||category==='Household'){const host=category==='Personal care'?'world.openbeautyfacts.org':'world.openproductsfacts.org';const params=new URLSearchParams({search_terms:q,search_simple:'1',action:'process',json:'1',page_size:'12',fields:'code,product_name,product_name_en,brands,quantity'});const d=await getJSON('https://'+host+'/cgi/search.pl?'+params);results.push(...(d.products||[]).map((p:any)=>mapProduct(p,category==='Personal care'?'Open Beauty Facts':'Open Products Facts',host)).filter(Boolean));}
else{const params=new URLSearchParams({q:q.replace(/\blite\b/gi,'light').replace(/[^\p{L}\p{N}\s.-]/gu,' '),page_size:'12',fields:'code,product_name,product_name_en,brands,quantity,countries_tags',langs:'en'});const d=await getJSON('https://search.openfoodfacts.org/search?'+params);const hits=(d.hits||[]).sort((a:any,b:any)=>Number((b.countries_tags||[]).includes('en:australia'))-Number((a.countries_tags||[]).includes('en:australia')));results.push(...hits.map((p:any)=>mapProduct(p,'Open Food Facts')).filter(Boolean));}
}catch{warning='The online catalogue is unavailable right now. You can try again, search the web, or enter the details below.';}
const data={results:results.slice(0,13),warning,queriedAt:Date.now()};return Response.json(data,{headers:{'Cache-Control':'no-store'}});}catch(e){return errorResponse(e);}}
