export type Batch={id:string;quantity:number;expiry:string;dateType:string;openedAt:number|null;afterOpeningDays:number|null};
export type Product={id:string;name:string;category:string;brand:string;variant:string;sku:string;barcode?:string;productName?:string;productUrl?:string;productSource?:string;aliases:string;unit:string;packSize:number|null;dailyUse:number|null;leadDays:number;bufferDays:number;targetDays:number;stockKnown:boolean;stockAt:number;lastCountAt:number|null;batches:Batch[];shopping:boolean;archived:boolean;notes:string;version:number};
export const units=['mL','L','g','kg','items','capsules','tablets','strips','sachets','servings','sprays'];
export const categories=['Groceries','Household','Personal care','Health care','Supplements'];
export const DAY=86400000;
export function sydneyDate(t=Date.now()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Sydney',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t));}
export function dateDeadline(date:string){const next=Date.parse(date+'T00:00:00Z')+DAY;let result=next;for(let i=0;i<3;i++){const z=new Intl.DateTimeFormat('en',{timeZone:'Australia/Sydney',timeZoneName:'shortOffset'}).formatToParts(new Date(result)).find(x=>x.type==='timeZoneName')?.value||'GMT+10';const offset=Number(z.replace('GMT',''));result=next-offset*3600000;}return result;}
export function deadline(b:Batch){const printed=b.expiry?dateDeadline(b.expiry):Infinity;const opened=b.openedAt&&b.afterOpeningDays?b.openedAt+b.afterOpeningDays*DAY:Infinity;return Math.min(printed,opened);}
export function advance(input:Batch[],from:number,to:number,rate:number){const b=structuredClone(input);let cursor=from;const points=[...new Set(b.map(deadline).filter(t=>t>from&&t<to)),to].sort((a,b)=>a-b);for(const end of points){let use=Math.max(0,(end-cursor)/DAY)*Math.max(0,rate);for(const lot of [...b].sort((a,b)=>deadline(a)-deadline(b))){if(deadline(lot)<=cursor)continue;const take=Math.min(lot.quantity,use);lot.quantity=Math.max(0,lot.quantity-take);use-=take;if(use<=0)break;}cursor=end;}return b;}
export function project(p:Product,now=Date.now()){const batches=advance(p.batches,p.stockAt,now,p.dailyUse||0);const usable=batches.filter(b=>deadline(b)>now);const quantity=usable.reduce((s,b)=>s+b.quantity,0);const expired=batches.filter(b=>deadline(b)<=now).reduce((s,b)=>s+b.quantity,0);let days:number|null=null;if(p.stockKnown&&p.dailyUse&&p.dailyUse>0){let remaining=structuredClone(usable),prev=now;const maxDays=Math.min(3660,quantity/p.dailyUse+1);const checkpoints=[...new Set(remaining.map(deadline).filter(x=>x>now&&x<now+maxDays*DAY)),now+maxDays*DAY].sort((a,b)=>a-b);for(const t of checkpoints){const sum=remaining.filter(b=>deadline(b)>prev).reduce((s,b)=>s+b.quantity,0);const depletion=prev+sum/p.dailyUse*DAY;if(depletion<=t){days=Math.max(0,(depletion-now)/DAY);break;}remaining=advance(remaining,prev,t,p.dailyUse).filter(b=>deadline(b)>t);prev=t;if(!remaining.length){days=(t-now)/DAY;break;}}}const threshold=p.leadDays+p.bufferDays+1;let state='setup';if(p.stockKnown){state=quantity<=0?'empty':days===null?'check':days<=threshold?'low':'okay';}const nextExpiry=usable.filter(b=>b.quantity>0&&Number.isFinite(deadline(b))).sort((a,b)=>deadline(a)-deadline(b))[0];const need=p.stockKnown&&p.dailyUse?Math.max(0,p.targetDays*p.dailyUse-quantity):null;let packs=need!==null&&p.packSize?Math.ceil(need/p.packSize):null;if(packs!==null&&p.dailyUse&&p.packSize&&(packs*p.packSize+quantity)/p.dailyUse>p.targetDays) packs=Math.floor(need!/p.packSize);return {batches,quantity,expired,days,state,threshold,nextExpiry:nextExpiry?deadline(nextExpiry):null,need,packs};}
export function freshProduct(id:string,name:string,category='Groceries',notes=''):Product{return {id,name,category,brand:'',variant:'',sku:'',aliases:'',unit:'',packSize:null,dailyUse:null,leadDays:2,bufferDays:3,targetDays:30,stockKnown:false,stockAt:Date.now(),lastCountAt:null,batches:[],shopping:false,archived:false,notes,version:0};}
export function formatQty(n:number){return new Intl.NumberFormat('en-AU',{maximumFractionDigits:2}).format(n);}
export function parseUpdate(text:string,products:Product[]){const lower=text.toLowerCase().replace(/[’']/g,'');const candidates=products.filter(p=>!p.archived&&[p.name,...p.aliases.split(',')].filter(x=>x.trim()).some(x=>lower.includes(x.trim().toLowerCase())));let kind= /\b(bought|buy|purchased|received|got)\b/.test(lower)?'purchase':/\b(finished|empty|ran out)\b/.test(lower)?'finish':/\b(opened|opening)\b/.test(lower)?'open':/\b(have|left|remaining|count)\b/.test(lower)?'count':'';let replaced=lower.replace(/\b(one|two|three|four|five|six|seven|eight|nine|ten|half)\b/g,x=>String(({one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,half:.5} as any)[x]));const quantityPattern=/(\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?|\.\d+)\s*(millilit(?:re|er)s?|ml|lit(?:re|er)s?|l\b|kilograms?|kg|grams?|g\b|bottles?|packs?|cartons?|items?|capsules?|tablets?|strips?|sachets?|servings?|sprays?)/gi;const matches=[...replaced.matchAll(quantityPattern)];const match=matches.length===1&&!/\d\s*(?:x|×|times)\s*\d/.test(replaced)?matches[0]:null;let quantity=match?Number(match[1].replaceAll(',','')):null;let rawUnit=match?.[2]||'';let unit=rawUnit.startsWith('m')?'mL':/^l/.test(rawUnit)?'L':/^k/.test(rawUnit)?'kg':/^g/.test(rawUnit)?'g':/bottle|pack|carton/.test(rawUnit)?'packs':rawUnit.replace(/s?$/,'s');let p=candidates.length===1?candidates[0]:null;if(p&&quantity!==null){const factors:Record<string,[string,number]>={L:['volume',1000],mL:['volume',1],kg:['weight',1000],g:['weight',1]};if(unit==='packs'&&p.packSize){quantity*=p.packSize;unit=p.unit;}else if(factors[unit]&&factors[p.unit]&&factors[unit][0]===factors[p.unit][0]){quantity=quantity*factors[unit][1]/factors[p.unit][1];unit=p.unit;}}
return {productId:p?.id||'',kind,quantity,unit,ambiguous:candidates.length>1,original:text};}
